version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: ["streamlit", "run", "application/app.py",  "--server.port", "8080"]
  test:
    build: .
    volumes:
      - .:/app
    command: ["pytest", "tests/test.py"]

